version: "3.9"

services:
  kasir:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kasir
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql